### ISSUE TITLE
Linux v1.01 binary path problem

### ISSUE THREAD

**Issue by skyler237** [BYU-PCCL/HolodeckPythonBinding#13]
The v1.01 binary path has an extra "LinuxNoEditor" in the path, making it something like ".../Holodeck/worlds/LinuxDefaultWorlds/LinuxNoEditor/LinuxNoEditor/..."

**Comment by joshgreaves** [comment]
I fixed it.
Anyone that was affected by this should remove their Holodeck directory wherever they installed it, and then re-run the install script.
