### ISSUE TITLE
Location Sensor initialization and scale

### ISSUE THREAD

**Issue by skyler237** [BYU-PCCL/HolodeckPythonBinding#14]
The location sensor doesn't initialize to zero (which seems like it would be ideal) and the data seems to be given in centimeters while the altitude command is given in meters. Is this intentional?

**Comment by joshgreaves** [comment]
Thanks for the report. You're right on both accounts. I'll fix both of these for the next build.

**Comment by joshgreaves** [comment]
Looks like the changes were included with the latest build.
Also, I added a pre-build check to ensure that the primary agent starts at location 0, 0, 0.
