### ISSUE TITLE
Roll command sign error

### ISSUE THREAD

**Issue by skyler237** [BYU-PCCL/HolodeckPythonBinding#15]
In order to produce a roll to the right, I need to give the simulation a negative roll command. Reading the state back from the orientation sensor gives a positive roll angle of equal magnitude, but opposite sign to the roll command. It seems as though there is a sign or direction error in the roll control code.

**Comment by joshgreaves** [comment]
After thinking about this we've decided to put everything into line with the Unreal Axes, that is positive x is forward, positive y is right, and positive z is up.

**Comment by mitchneutron** [comment]
@skyler237 To clarify, are you using the OrientationSensor or the IMUSensor? The OrientationSensor gives three vectors: the up, right, and forward vector, which can be used to calculate the exact orientation of the UAV, whereas the IMUSensor gives linear acceleration and angular velocity. Are you using one or the other to personally calculate the roll angle, or am I mistaken with something?

**Comment by mitchneutron** [comment]
@skyler237 Update: I built a RotationSensor to test it, and you are right. A positive roll command yields a negative roll value. We'll be looking into it more.

**Comment by joshgreaves** [comment]
@mitchneutron has this been fixed?

**Comment by mitchneutron** [comment]
No it has not

**Comment by mitchneutron** [comment]
This should be fixed in the next update.
