### ISSUE TITLE
Holodeck Worlds

### ISSUE THREAD

**Issue by pmarke** [BYU-PCCL/HolodeckPythonBinding#26]
I installed the latest version of Holodeck, and I am no longer able to load any worlds. They simply are not found.

**Comment by mitchneutron** [comment]
Hey I’ve been looking to narrow down why this is happening. Do you get any errors thrown by the install script or does it state that the install was successful?

**Comment by pmarke** [comment]
It says that it was successful

**Comment by mitchneutron** [comment]
Okay, so I think I found what was going on. It was definitely a problem on our end. If you try it again then it should work correctly. The updated code expected a json file for configurations, but the packaged world didn't have that json file. We've now updated both the code and the worlds.

**Comment by mitchneutron** [comment]
I'm marking this as closed as the bug should be gone.
