### ISSUE TITLE
Binary mismatch for json loading

### ISSUE THREAD

**Issue by skyler237** [BYU-PCCL/HolodeckPythonBinding#27]
I think the install.py script needs to be updated to v1.02, which has the config.json file for the worlds. Currently, my holodeck.py is looking for a json file that isn't there (in v1.01).

Also, the config.json file for linux has ".../Holodeck.exe" instead of ".../Holodeck"

**Comment by mitchneutron** [comment]
Yeah it looks like that is the case. It should be good to go now! Let me know if anything else seems to be mistaken. It installs correctly on my machine now.
