### ISSUE TITLE
Expose Agent Hyperparameters

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/HolodeckPythonBinding#33]
For example, PID settings for UAV.
This should be fairly easy. Something like giving HolodeckAgent some "settings buffer", and have the child class define the size. Then, index into that buffer in C++ for each variable, setting the default values. Then connect to this buffer with Python and somewhere define what each index in the buffer corresponds to.
That's just an initial idea, if you can think of a better way, we can do it that way.

**Comment by nickwalton** [comment]
Added in command center update to develop branch.
