### ISSUE TITLE
Coordinates are left-hand and not centered at start

### ISSUE THREAD

**Issue by patrickwalton** [BYU-PCCL/HolodeckPythonBinding#42]
Currently the coordinate system appears to be left-hand, which makes it difficult to work with for robotic vision/controls.

Also, the starting location of the quadrotor appears arbitrary (in the 400s), would make more sense if it were zero.

**Comment by joshgreaves** [comment]
All coordinates are in the unreal coordinate frame. More will be added according to #91.
In the build instructions, worlds should be centered on the primary agent.
