### ISSUE TITLE
Issues with having default location be /usr/local

### ISSUE THREAD

**Issue by nickwalton** [BYU-PCCL/HolodeckPythonBinding#57]
I've noticed that by installing the worlds in /usr/local it can cause some issues with permissions as well as environment variables that are set. I think it would be easier if the worlds were just put inside the python binding folder.

**Comment by joshgreaves** [comment]
Holodeck is now installed with pip, so it is not placed in /usr/local.
Worlds are now installed to ~/.local/shared/holodeck/worlds in Linux systems.
