### ISSUE TITLE
OpenGL3 not working?

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/HolodeckPythonBinding#61]
I tried to run Holodeck with OpenGL3 since it warned me I don't have 4 installed. I got this error message still.
![image](https://user-images.githubusercontent.com/18729121/43843014-d1c0f8ca-9ae3-11e8-9719-f0551d9e80d1.png)

**Comment by nickwalton** [comment]
Is it worth it to try and support opengl3? Or should we just say that it requires opengl4?

**Comment by joshgreaves** [comment]
I think it was just an error with my OpenGL installation. It works using GL 3 or 4. I don’t know how to replicate this
