### ISSUE TITLE
Errors in built worlds

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/HolodeckPythonBinding#68]
EuropeanForest drone doesn't react to any commands.
UrbanCity doesn't seem to have a reward signal (at least, I didn't find any reward)

**Comment by joshgreaves** [comment]
Also, UrbanCity and CyberPunkCity don't react to any commands. Maybe it's just the UAV?

**Comment by nickwalton** [comment]
Turns out that it works if you call env.reset() before entering the loop. I'm not sure why that is, but it would be good to change so that isn't necessary.
